name: inventiv_critic_flutter
description: A flutter plugin for Critic integration.
version: 1.1.0
homepage: https://www.twinsunsolutions.com
repository: https://github.com/twinsunllc/inventiv-critic-flutter

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  mime: ^1.0.0
  battery_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
